# -*- coding: UTF-8 -*-
"""Build script for the Resource Manager NVDA add-on.

Produces resourceManager-<version>.nvda-addon in the repository root. Requires
nothing beyond a Python 3 interpreter: no SCons, no gettext, no markdown.

Usage:
        python build.py                 Build the add-on package.
        python build.py --dev-install   Build, then unpack straight into NVDA's
                                        add-ons folder for quick testing.
        python build.py --clean         Remove build output and generated files.

Written by CodedByGoose, with the help of Quill (Claude agent).
"""

import argparse
import html
import os
import re
import shutil
import sys
import zipfile

import buildVars

ROOT = os.path.dirname(os.path.abspath(__file__))
ADDON_DIR = os.path.join(ROOT, "addon")
INFO = buildVars.addon_info
ADDON_NAME = INFO["addon_name"]
VERSION = INFO["addon_version"]
PACKAGE_NAME = f"{ADDON_NAME}-{VERSION}.nvda-addon"

# Never ship these, whatever else happens to be in the addon folder.
ALWAYS_EXCLUDED_DIRS = {"__pycache__", ".git"}
ALWAYS_EXCLUDED_SUFFIXES = (".pyc", ".pyo")


def generateManifest():
    """Write addon/manifest.ini from the values in buildVars.py."""
    path = os.path.join(ADDON_DIR, "manifest.ini")
    updateChannel = INFO["addon_updateChannel"]
    lines = [
        "; Generated by build.py from buildVars.py. Do not edit by hand.",
        f"name = {ADDON_NAME}",
        f'summary = "{INFO["addon_summary"]}"',
        f'description = """{INFO["addon_description"]}"""',
        f'author = "{INFO["addon_author"]}"',
        f"url = {INFO['addon_url']}",
        f"version = {VERSION}",
        f"docFileName = {INFO['addon_docFileName']}",
        f"minimumNVDAVersion = {INFO['addon_minimumNVDAVersion']}",
        f"lastTestedNVDAVersion = {INFO['addon_lastTestedNVDAVersion']}",
        f"updateChannel = {updateChannel if updateChannel else 'None'}",
    ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return path


def markdownToHtml(text, title):
    """Convert the subset of Markdown used in our documentation into HTML.

    Deliberately small: headings, paragraphs, bullet lists, inline code, bold
    and links are all the readme uses, and this avoids a build dependency.
    """

    def inline(s):
        s = html.escape(s)
        s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
        s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
        s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', s)
        return s

    out = []
    paragraph = []
    inList = False

    def flushParagraph():
        if paragraph:
            out.append("<p>" + inline(" ".join(paragraph)) + "</p>")
            paragraph.clear()

    def closeList():
        nonlocal inList
        if inList:
            out.append("</ul>")
            inList = False

    for rawLine in text.splitlines():
        line = rawLine.rstrip()
        heading = re.match(r"^(#{1,6})\s+(.*)$", line)
        bullet = re.match(r"^[-*]\s+(.*)$", line)
        if not line.strip():
            flushParagraph()
            closeList()
        elif heading:
            flushParagraph()
            closeList()
            level = len(heading.group(1))
            out.append(f"<h{level}>{inline(heading.group(2))}</h{level}>")
        elif bullet:
            flushParagraph()
            if not inList:
                out.append("<ul>")
                inList = True
            out.append("<li>" + inline(bullet.group(1)) + "</li>")
        elif inList:
            # A wrapped continuation line belonging to the current list item.
            out[-1] = out[-1][: -len("</li>")] + " " + inline(line.strip()) + "</li>"
        else:
            paragraph.append(line.strip())
    flushParagraph()
    closeList()

    body = "\n".join(out)
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="UTF-8">\n'
        f"<title>{html.escape(title)}</title>\n</head>\n<body>\n{body}\n</body>\n</html>\n"
    )


def generateDocs():
    """Render each addon/doc/<lang>/readme.md into readme.html beside it."""
    docRoot = os.path.join(ADDON_DIR, "doc")
    generated = []
    if not os.path.isdir(docRoot):
        return generated
    title = f"{INFO['addon_summary']} {VERSION}"
    for lang in sorted(os.listdir(docRoot)):
        source = os.path.join(docRoot, lang, "readme.md")
        if not os.path.isfile(source):
            continue
        with open(source, encoding="utf-8") as f:
            markdown = f.read()
        target = os.path.join(docRoot, lang, "readme.html")
        with open(target, "w", encoding="utf-8") as f:
            f.write(markdownToHtml(markdown, title))
        generated.append(target)
    return generated


def shouldInclude(relativePath):
    parts = relativePath.replace("\\", "/").split("/")
    if any(part in ALWAYS_EXCLUDED_DIRS for part in parts):
        return False
    if relativePath.endswith(ALWAYS_EXCLUDED_SUFFIXES):
        return False
    # readme.md is the source for readme.html; only the rendered copy ships.
    if parts[-1] == "readme.md":
        return False
    if relativePath.replace("\\", "/") in buildVars.excludedFiles:
        return False
    return True


def collectFiles():
    for dirPath, dirNames, fileNames in os.walk(ADDON_DIR):
        dirNames[:] = [d for d in dirNames if d not in ALWAYS_EXCLUDED_DIRS]
        for fileName in fileNames:
            fullPath = os.path.join(dirPath, fileName)
            relativePath = os.path.relpath(fullPath, ADDON_DIR)
            if shouldInclude(relativePath):
                yield fullPath, relativePath.replace("\\", "/")


def build():
    generateManifest()
    generateDocs()
    target = os.path.join(ROOT, PACKAGE_NAME)
    if os.path.exists(target):
        os.remove(target)
    count = 0
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as archive:
        for fullPath, arcName in collectFiles():
            archive.write(fullPath, arcName)
            count += 1
    print(f"Built {PACKAGE_NAME} ({count} files, {os.path.getsize(target):,} bytes)")
    return target


def devInstall(packagePath):
    """Unpack the built add-on straight into NVDA's user add-ons folder."""
    addonsDir = os.path.join(os.environ["APPDATA"], "nvda", "addons")
    if not os.path.isdir(addonsDir):
        sys.exit(f"NVDA add-ons folder not found: {addonsDir}")
    target = os.path.join(addonsDir, ADDON_NAME)
    if os.path.exists(target):
        try:
            shutil.rmtree(target)
        except OSError as e:
            sys.exit(
                f"Could not replace {target}: {e}\n"
                "NVDA is probably holding the old copy open. Exit NVDA and try again."
            )
    with zipfile.ZipFile(packagePath) as archive:
        archive.extractall(target)
    print(f"Installed to {target}")
    print("Restart NVDA, or press NVDA+control+F3 to reload plugins.")


def clean():
    removed = []
    for name in os.listdir(ROOT):
        if name.endswith(".nvda-addon"):
            os.remove(os.path.join(ROOT, name))
            removed.append(name)
    manifest = os.path.join(ADDON_DIR, "manifest.ini")
    if os.path.exists(manifest):
        os.remove(manifest)
        removed.append("addon/manifest.ini")
    docRoot = os.path.join(ADDON_DIR, "doc")
    if os.path.isdir(docRoot):
        for lang in os.listdir(docRoot):
            generated = os.path.join(docRoot, lang, "readme.html")
            if os.path.exists(generated):
                os.remove(generated)
                removed.append(f"addon/doc/{lang}/readme.html")
    for dirPath, _dirNames, _fileNames in os.walk(ROOT):
        if os.path.basename(dirPath) == "__pycache__":
            shutil.rmtree(dirPath, ignore_errors=True)
    print("Removed: " + (", ".join(removed) if removed else "nothing to clean"))


def main():
    parser = argparse.ArgumentParser(description="Build the Resource Manager NVDA add-on.")
    parser.add_argument(
        "--dev-install",
        action="store_true",
        help="unpack into NVDA's add-ons folder after building",
    )
    parser.add_argument("--clean", action="store_true", help="remove build output and generated files")
    args = parser.parse_args()
    if args.clean:
        clean()
        return
    package = build()
    if args.dev_install:
        devInstall(package)


if __name__ == "__main__":
    main()
