"""Compare two built .nvda-addon packages for equivalence.

Zip archives record file timestamps, so two builds of the same source never
match byte for byte. This compares what actually matters instead: the file
list, the bytes of every packaged file, and every manifest field.

Used to check that a change to the build system did not change what ships.
It was written for the migration onto NV Access's add-on template and is kept
for the next template update.

    python tests/comparePackages.py reference.nvda-addon taskExplorer-1.0.2.nvda-addon

Exits 0 when the two packages are equivalent, 1 when they are not.
Differences in generated documentation are reported but do not fail the
comparison, since the HTML is regenerated by a different Markdown pipeline.
"""

import sys
import zipfile

# Manifest fields that must be identical between the two packages.
MANIFEST_FIELDS = [
    "name",
    "version",
    "summary",
    "description",
    "author",
    "url",
    "docFileName",
    "minimumNVDAVersion",
    "lastTestedNVDAVersion",
    "changelog",
]

# Entries that are allowed to differ, or to be present in only one package.
# Documentation is generated by the build, so which files it produces and what
# is in them are both expected to change when the build system changes.
GENERATED = ("doc/",)


def readManifest(archive):
    """Return the manifest of an archive as a dict of field name to value.

    NVDA manifests are not quite ini files: values may be bare, double quoted,
    or triple quoted and spanning several lines, which configparser cannot read.
    """
    lines = archive.read("manifest.ini").decode("utf-8").splitlines()
    fields = {}
    index = 0
    while index < len(lines):
        line = lines[index]
        index += 1
        if not line.strip() or line.lstrip().startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if value.startswith('"""'):
            collected = [value[3:]]
            while not collected[-1].endswith('"""') and index < len(lines):
                collected.append(lines[index])
                index += 1
            collected[-1] = collected[-1].removesuffix('"""')
            fields[key] = "\n".join(collected).strip()
        else:
            fields[key] = value.strip('"').strip()
    return fields


def compare(referencePath, candidatePath):
    """Compare two packages. Returns a list of failure messages, empty if equivalent."""
    failures = []
    notes = []

    with zipfile.ZipFile(referencePath) as reference, zipfile.ZipFile(candidatePath) as candidate:
        referenceNames = set(reference.namelist())
        candidateNames = set(candidate.namelist())

        for name in sorted(referenceNames - candidateNames):
            if name.startswith(GENERATED):
                notes.append(f"absent, generated: {name}")
            else:
                failures.append(f"missing from {candidatePath}: {name}")
        for name in sorted(candidateNames - referenceNames):
            if name.startswith(GENERATED):
                notes.append(f"added, generated: {name}")
            else:
                failures.append(f"unexpected in {candidatePath}: {name}")

        for name in sorted(referenceNames & candidateNames):
            if name == "manifest.ini":
                continue
            if reference.read(name) == candidate.read(name):
                continue
            if name.startswith(GENERATED):
                notes.append(f"differs, generated: {name}")
            else:
                failures.append(f"contents differ: {name}")

        referenceManifest = readManifest(reference)
        candidateManifest = readManifest(candidate)

    for field in MANIFEST_FIELDS:
        expected = referenceManifest.get(field)
        actual = candidateManifest.get(field)
        if expected != actual:
            failures.append(f"manifest field {field} differs:\n  reference: {expected!r}\n  candidate: {actual!r}")

    for note in notes:
        print(note)

    return failures


def main(argv):
    if len(argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2

    failures = compare(argv[1], argv[2])
    if failures:
        print(f"\n{len(failures)} difference(s):", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 1

    print(f"\n{argv[2]} is equivalent to {argv[1]}.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
